[package]
name = "img-editor-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
image = "0.24"
imageproc = "0.23"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5"
ab_glyph = "0.2"